### ISSUE TITLE
connection to data always refused

### ISSUE THREAD

**Issue by jasonwangnanjing** [chenfromsz/spring-boot-ui#1]
Hi Mr.Chen,
I bought the book.But the code i pull from here could not work. I started the application from module webui's webuiapp.Then i can visit pages from broswer.But it popup error that connection refused. 
Do u have the same issue in your local env? can u please correct the code or provide issue fix hints?

BR Jason

**Comment by chenfromsz** [comment]
You can change the password to connect to the database in the configuration file, or change the connection to the database to be consistent with the configuration file.

**Comment by jasonwangnanjing** [comment]
tks.fixed
